name: Publish
on:
  release:
    types: [published]

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" >> .npmrc
      - uses: ./.github/actions/install
      - run: pnpm build
      - run: pnpm publish --no-git-checks --access public --provenance
